version: "3.9"
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg_lab_pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: user@acme.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_CONFIG_SERVER_MODE: "True"

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:

